// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  gameCode: __t.string().name("game_code"),
  name: __t.string(),
  imageData: __t.string().name("image_data"),
  uploadedBy: __t.identity().name("uploaded_by"),
  uploadedByName: __t.string().name("uploaded_by_name"),
});
