// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  code: __t.string().primaryKey(),
  groupName: __t.string().name("group_name"),
  creator: __t.identity(),
  status: __t.string(),
  mode: __t.string(),
  weeksTotal: __t.u32().name("weeks_total"),
  currentWeek: __t.u32().name("current_week"),
  phase: __t.string(),
  phaseEndsAt: __t.u64().name("phase_ends_at"),
  targetPayment: __t.u32().name("target_payment"),
  totalMora: __t.u32().name("total_mora"),
  weeksMissed: __t.u32().name("weeks_missed"),
});
