// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  gameCode: __t.string().name("game_code"),
  playerIdentity: __t.identity().name("player_identity"),
  objectiveKey: __t.string().name("objective_key"),
  description: __t.string(),
  completed: __t.bool(),
  bonusMoney: __t.i32().name("bonus_money"),
  bonusScore: __t.i32().name("bonus_score"),
});
