// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const BusinessEvent = __t.object("BusinessEvent", {
  id: __t.u64(),
  gameCode: __t.string(),
  playerIdentity: __t.identity(),
  week: __t.u32(),
  eventKey: __t.string(),
  moneyDelta: __t.i32(),
  message: __t.string(),
});
export type BusinessEvent = __Infer<typeof BusinessEvent>;

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  gameCode: __t.string(),
  senderIdentity: __t.identity(),
  senderName: __t.string(),
  content: __t.string(),
  kind: __t.string(),
  sentAt: __t.u64(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const CustomSticker = __t.object("CustomSticker", {
  id: __t.u64(),
  gameCode: __t.string(),
  name: __t.string(),
  imageData: __t.string(),
  uploadedBy: __t.identity(),
  uploadedByName: __t.string(),
});
export type CustomSticker = __Infer<typeof CustomSticker>;

export const Game = __t.object("Game", {
  code: __t.string(),
  groupName: __t.string(),
  creator: __t.identity(),
  status: __t.string(),
  mode: __t.string(),
  weeksTotal: __t.u32(),
  currentWeek: __t.u32(),
  phase: __t.string(),
  phaseEndsAt: __t.u64(),
  targetPayment: __t.u32(),
  totalMora: __t.u32(),
  weeksMissed: __t.u32(),
});
export type Game = __Infer<typeof Game>;

export const GameEvent = __t.object("GameEvent", {
  id: __t.u64(),
  gameCode: __t.string(),
  kind: __t.string(),
  message: __t.string(),
});
export type GameEvent = __Infer<typeof GameEvent>;

export const Payment = __t.object("Payment", {
  id: __t.u64(),
  gameCode: __t.string(),
  playerIdentity: __t.identity(),
  week: __t.u32(),
  amount: __t.u32(),
  choice: __t.string(),
});
export type Payment = __Infer<typeof Payment>;

export const Player = __t.object("Player", {
  id: __t.u64(),
  identity: __t.identity(),
  gameCode: __t.string(),
  name: __t.string(),
  businessType: __t.string(),
  pronoun: __t.string(),
  loanSize: __t.string(),
  weeklyPayment: __t.u32(),
  money: __t.i32(),
  online: __t.bool(),
});
export type Player = __Infer<typeof Player>;

export const SecretObjective = __t.object("SecretObjective", {
  id: __t.u64(),
  gameCode: __t.string(),
  playerIdentity: __t.identity(),
  objectiveKey: __t.string(),
  description: __t.string(),
  completed: __t.bool(),
  bonusMoney: __t.i32(),
});
export type SecretObjective = __Infer<typeof SecretObjective>;

export const SolidarioTransfer = __t.object("SolidarioTransfer", {
  id: __t.u64(),
  gameCode: __t.string(),
  senderIdentity: __t.identity(),
  receiverIdentity: __t.identity(),
  week: __t.u32(),
  amount: __t.u32(),
});
export type SolidarioTransfer = __Infer<typeof SolidarioTransfer>;

export const WeekResult = __t.object("WeekResult", {
  id: __t.u64(),
  gameCode: __t.string(),
  week: __t.u32(),
  totalPaid: __t.u32(),
  target: __t.u32(),
  passed: __t.bool(),
  moraAdded: __t.u32(),
});
export type WeekResult = __Infer<typeof WeekResult>;

